# Generated by Django 5.1.3 on 2025-02-21 20:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10, unique=True)),
                ('competition_id', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'aircraft',
                'verbose_name_plural': 'aircraft',
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=20, null=True)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invoicing.account')),
                ('refund_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_events', to='invoicing.accountentry')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.baseevent')),
                ('takeoff_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('takeoff_location', models.CharField(blank=True, max_length=50, null=True)),
                ('landing_location', models.CharField(blank=True, max_length=50, null=True)),
                ('landing_count', models.PositiveIntegerField(default=1)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purpose', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('surcharge_reason', models.TextField(blank=True, null=True)),
                ('discount_reason', models.TextField(blank=True, null=True)),
                ('captain', models.CharField(blank=True, max_length=100, null=True, verbose_name='PIC')),
                ('passengers', models.TextField(blank=True, help_text='List of passengers on the flight', null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='operations.aircraft')),
            ],
            options={
                'db_table': 'flights',
                'constraints': [models.UniqueConstraint(fields=('aircraft', 'takeoff_time', 'landing_time'), name='flight_time_slot_per_aircraft_unique')],
            },
            bases=('operations.baseevent',),
        ),
    ]
